export {
  AiBeautifyIcon,
  AiGenerativeIcon,
  ApiIcon,
  ArchiveRestoreIcon,
  Bug01Icon as BugIcon,
  ComputerSettingsIcon,
  DatabaseAddIcon,
  DiscoverCircleIcon,
  Download06Icon as DownloadIcon,
  Edit02Icon as EditIcon,
  GithubIcon,
  InformationCircleIcon,
  Moon02Icon as MoonIcon,
  PanelLeftCloseIcon,
  PanelLeftOpenIcon,
  PlayCircleIcon,
  PlayIcon,
  SaveIcon,
  Settings03Icon as SettingsIcon,
  Sun03Icon as SunIcon,
  TaskDone01Icon as TaskDoneIcon,
  TypeCursorIcon,
  UnavailableIcon,
  Upload06Icon as UploadIcon,
} from "@hugeicons/core-free-icons";
