export {
  Settings03Icon as SettingsIcon,
  Sun03Icon as SunIcon,
  Moon02Icon as MoonIcon,
  ComputerSettingsIcon,
  SaveIcon,
  Download06Icon as DownloadIcon,
  Upload06Icon as UploadIcon,
  GithubIcon as GithubIcon,
  DiscoverCircleIcon,
  PlayCircleIcon,
  TaskDone01Icon as TaskDoneIcon,
  ApiIcon,
  PanelLeftCloseIcon,
  PanelLeftOpenIcon,
  PlayIcon,
  TypeCursorIcon,
  DatabaseAddIcon,
  InformationCircleIcon,
  ArchiveRestoreIcon,
  Edit02Icon as EditIcon,
  Bug01Icon as BugIcon,
  UnavailableIcon,
} from "@hugeicons/core-free-icons";
