/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteRouteImport } from './routes/index/route'
import { Route as CelRouteImport } from './routes/cel'
import { Route as JmespathRouteImport } from './routes/jmespath'
import { Route as JqRouteImport } from './routes/jq'
import { Route as JsonTableRouteImport } from './routes/json-table'
import { Route as JsonpathRouteImport } from './routes/jsonpath'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as SqlRouteRouteImport } from './routes/sql/route'
import { Route as TextConverterRouteRouteImport } from './routes/text-converter/route'
import { Route as ApiAiGenerateRouteImport } from './routes/api/ai/generate'
import { Route as ApiChatgptSplatRouteImport } from './routes/api/chatgpt/$'

const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const CelRoute = CelRouteImport.update({
  id: '/cel',
  path: '/cel',
  getParentRoute: () => rootRouteImport,
} as any)
const JmespathRoute = JmespathRouteImport.update({
  id: '/jmespath',
  path: '/jmespath',
  getParentRoute: () => rootRouteImport,
} as any)
const JqRoute = JqRouteImport.update({
  id: '/jq',
  path: '/jq',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonTableRoute = JsonTableRouteImport.update({
  id: '/json-table',
  path: '/json-table',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonpathRoute = JsonpathRouteImport.update({
  id: '/jsonpath',
  path: '/jsonpath',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlRouteRoute = SqlRouteRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => rootRouteImport,
} as any)
const TextConverterRouteRoute = TextConverterRouteRouteImport.update({
  id: '/text-converter',
  path: '/text-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateRoute = ApiAiGenerateRouteImport.update({
  id: '/api/ai/generate',
  path: '/api/ai/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatgptSplatRoute = ApiChatgptSplatRouteImport.update({
  id: '/api/chatgpt/$',
  path: '/api/chatgpt/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/settings': typeof SettingsRouteRoute
  '/sql': typeof SqlRouteRoute
  '/text-converter': typeof TextConverterRouteRoute
  '/cel': typeof CelRoute
  '/jmespath': typeof JmespathRoute
  '/jq': typeof JqRoute
  '/json-table': typeof JsonTableRoute
  '/jsonpath': typeof JsonpathRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/chatgpt/$': typeof ApiChatgptSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/settings': typeof SettingsRouteRoute
  '/sql': typeof SqlRouteRoute
  '/text-converter': typeof TextConverterRouteRoute
  '/cel': typeof CelRoute
  '/jmespath': typeof JmespathRoute
  '/jq': typeof JqRoute
  '/json-table': typeof JsonTableRoute
  '/jsonpath': typeof JsonpathRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/chatgpt/$': typeof ApiChatgptSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/settings': typeof SettingsRouteRoute
  '/sql': typeof SqlRouteRoute
  '/text-converter': typeof TextConverterRouteRoute
  '/cel': typeof CelRoute
  '/jmespath': typeof JmespathRoute
  '/jq': typeof JqRoute
  '/json-table': typeof JsonTableRoute
  '/jsonpath': typeof JsonpathRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/chatgpt/$': typeof ApiChatgptSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/sql'
    | '/text-converter'
    | '/cel'
    | '/jmespath'
    | '/jq'
    | '/json-table'
    | '/jsonpath'
    | '/api/ai/generate'
    | '/api/chatgpt/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/sql'
    | '/text-converter'
    | '/cel'
    | '/jmespath'
    | '/jq'
    | '/json-table'
    | '/jsonpath'
    | '/api/ai/generate'
    | '/api/chatgpt/$'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/sql'
    | '/text-converter'
    | '/cel'
    | '/jmespath'
    | '/jq'
    | '/json-table'
    | '/jsonpath'
    | '/api/ai/generate'
    | '/api/chatgpt/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  SettingsRouteRoute: typeof SettingsRouteRoute
  SqlRouteRoute: typeof SqlRouteRoute
  TextConverterRouteRoute: typeof TextConverterRouteRoute
  CelRoute: typeof CelRoute
  JmespathRoute: typeof JmespathRoute
  JqRoute: typeof JqRoute
  JsonTableRoute: typeof JsonTableRoute
  JsonpathRoute: typeof JsonpathRoute
  ApiAiGenerateRoute: typeof ApiAiGenerateRoute
  ApiChatgptSplatRoute: typeof ApiChatgptSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cel': {
      id: '/cel'
      path: '/cel'
      fullPath: '/cel'
      preLoaderRoute: typeof CelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jmespath': {
      id: '/jmespath'
      path: '/jmespath'
      fullPath: '/jmespath'
      preLoaderRoute: typeof JmespathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jq': {
      id: '/jq'
      path: '/jq'
      fullPath: '/jq'
      preLoaderRoute: typeof JqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-table': {
      id: '/json-table'
      path: '/json-table'
      fullPath: '/json-table'
      preLoaderRoute: typeof JsonTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jsonpath': {
      id: '/jsonpath'
      path: '/jsonpath'
      fullPath: '/jsonpath'
      preLoaderRoute: typeof JsonpathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql': {
      id: '/sql'
      path: '/sql'
      fullPath: '/sql'
      preLoaderRoute: typeof SqlRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-converter': {
      id: '/text-converter'
      path: '/text-converter'
      fullPath: '/text-converter'
      preLoaderRoute: typeof TextConverterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate': {
      id: '/api/ai/generate'
      path: '/api/ai/generate'
      fullPath: '/api/ai/generate'
      preLoaderRoute: typeof ApiAiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chatgpt/$': {
      id: '/api/chatgpt/$'
      path: '/api/chatgpt/$'
      fullPath: '/api/chatgpt/$'
      preLoaderRoute: typeof ApiChatgptSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  SettingsRouteRoute: SettingsRouteRoute,
  SqlRouteRoute: SqlRouteRoute,
  TextConverterRouteRoute: TextConverterRouteRoute,
  CelRoute: CelRoute,
  JmespathRoute: JmespathRoute,
  JqRoute: JqRoute,
  JsonTableRoute: JsonTableRoute,
  JsonpathRoute: JsonpathRoute,
  ApiAiGenerateRoute: ApiAiGenerateRoute,
  ApiChatgptSplatRoute: ApiChatgptSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
